### PR TITLE
Updating the URL to reflect default child states being displayed

### PR DESCRIPTION
**Pull request by TehShrike**
Didn't turn out to be too bad.  Any thoughts @ArtskydJ or @thebearingedge?

### CODE REVIEW

**Comment by thebearingedge** [comment]
When I use this branch in my project I can't get any default children to render if they are missing a `route` value:

This is working over in master.

```javascript
router.addState({
  name: 'root',
  route: '/',
  defaultChild: 'app',
  template: 'app-container'
});
router.addState({
  name: 'root.app',
  defaultChild: 'home',
  template: 'app-main'
});
router.addState({
  name: 'root.app.home',
  template: 'app-home'
});
// going to "/" should still give the full tree of <ui-view>'s, no?
```

This PR addresses the issue of the hash reflecting child routes, but now you *have* to include them.

```javascript
router.addState({
  name: 'root',
  route: '/',
  defaultChild: 'app',
  template: 'app-container'
});
router.addState({
  name: 'root.app',
  route: 'app',
  defaultChild: 'home',
  template: 'app-main'
});
router.addState({
  name: 'root.app.home',
  route: 'home',
  template: 'app-home'
});
// "/" redirects to "/app/home"
```

If a child state's route property is undefined or empty, the child won't render for me.
Also, loading the app on a bad route such as `/app/home/asdf` now just prevents anything from showing up. Before it would at least render the fallback state, but not update the hash.

I'm sorry, I would submit tests but I've never used tape and haven't learned the codebase yet. Will keep looking it over.

**Comment by thebearingedge** [comment]
The goal in my code above is to be able to switch out the entire "container" for different areas of the app, e.g. Application, Login, Admin without having to put something meaningless like "app" or "home" in the URL. Maybe a minor quibble, but the only purpose that route would serve is getting application chrome on the screen.

What I currently do with UI Router:
-App `/` (resolve authentication)
  -Overview (or some default landing screen, default view)
  -Sales `/sales`
  -Purchasing `/purchasing`
-Admin `/admin` (resolve authorization)
-Login `/login`

**Comment by TehShrike** [comment]
This pull request as it exists at the moment changes the behavior so that default child states are only accessible by their url route - the problem being that in your example above, `root`, `root.app`, and `root.app.home` all share the same route.

Right now the hash-brown-router doesn't do any de-duplication of routes - they're all just appended to [an array](https://github.com/TehShrike/hash-brown-router/blob/master/index.js#L12), and then [array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) is used to find the first matching one.

The abstract-state-router already requires you to have to have added parent states before adding child states [if you want the routing to work](https://github.com/TehShrike/abstract-state-router/blob/master/index.js#L118-L120), so this particular difficulty could be fixed by simply having the hash-brown-router evaluate routes starting with the most-recently added routes instead of going from oldest-to-newest.

Otherwise, de-duplicating the routes in a foolproof way is difficult.

This would still allow you to create ambiguous routes, but I don't think there's a way around that.  Specifically, with this setup:

```js
router.addState({
  name: 'root',
  route: '/',
  defaultChild: 'app',
  template: 'app-container'
});
router.addState({
  name: 'root.app',
  template: 'app-main'
});
router.addState({
  name: 'root.login',
  template: 'login'
});
```

browsing to `/` would send you to `root.login`, because even though the `app` state is at route `/` and has a default child of `root.app`, all three states do have the same route, and `root.login` is the most recently-added one.

**Comment by TehShrike** [comment]
I've added that functionality to hash-brown-router - it can now match routes [in reverse](https://github.com/TehShrike/hash-brown-router#construction).  I've also [enabled that functionality in this branch](https://github.com/TehShrike/abstract-state-router/blob/change-route-on-default-child/index.js#L26).  Let me know what you think of that option @thebearingedge

**Comment by thebearingedge** [comment]
This PR looks good to me.

Regarding reverse lookup of routes in hash-brown-router, I don't think that helps my problem. I had a fundamental misunderstanding of how the library works.

**Comment by TehShrike** [comment]
All right, I'll merge this without reversing the route evaluation.

**Comment by TehShrike** [comment]
All right, this has been published as 5.2.0.  What was your original expectation for how the library would work @thebearingedge?

**Comment by thebearingedge** [comment]
I forgot how heavily I was using named views in UI-Router and immediately started trying to use abstract-state-router to accomplish the same effect.

For some context here is what I do in UI-Router:

```javascript

$stateProvider

  // to leave "/" for the 'app' state...
  .state('root', {
    abstract: true,
    url: ''
  })

  .state('app', {
    parent: 'root',
    url: '/',
    data: {
      loginRequired: true
    },
    views: {
     // 'page' view is on index.html
      'page@': {
        templateUrl: '/templates/app-layout.html',
        controller: 'AppLayoutController',
        controllerAs: 'app'
      },
     // 'navigation' view is within the 'app-layout' template
      'navigation@app': {
        templateUrl: '/templates/app-navbar.html',
        controller: 'AppNavbarController',
        controllerAs: 'navbar'
      }
    }
  })

  // 'login' state is a child of root, sibling to 'app'
  .state('login', {
    parent: 'root',
    url: '/login',
    views: {
      'page@': {
        templateUrl: '/templates/app-login.template.html',
        controller: 'AppLoginController',
        controllerAs: 'login'
      }
    }
  });

```

```jade
// index.jade
html
  body(ng-app='myApp')
    div.page(ui-view='page')
    script(src='main.js')
```

```jade
// app-layout.jade
div.app-layout
  div(ui-view='navigation')
  div.feature(ui-view)
    // some landing page content that displays at "/"
    span Hello App &nbsp;
```

In the above, my `app` state can target `<div ui-view="page">`, populate it with the `app-layout.html` template, which contains `<div ui-view="navigation">`, and specify the template for the navigation view as well. In addition to `<div ui-view="navigation">` the `app-layout.html` template contains a  `<div ui-view>` for nested routes.

I can't say that I had an expectation that abstract-state-router would work in this fashion, but I immediately started trying to use it to accomplish the above. Along the way I failed to recognize that child routes and child views are 1:1.

I am very excited at the idea of using a powerful, pluggable router. I just haven't figured out how to accomplish the above with abstract-state-router. Does that make sense? Am I thinking about the problem incorrectly? It wouldn't be the stupidest I've been.

**Comment by TehShrike** [comment]
aah, interesting.  I haven't yet used named views in Angular, I've generally used directives to make re-usable template module thingies.  When I originally read about named view functionality in ui-router I couldn't ever come up with a reason to use them, **but** I never really put much effort into finding a use case either.

What's the advantage over directives as you're using named views in your case?  Is it that the navigation view can inject all of the resolves/stateParams from the root.app state, and updates whenever the root.app params change?

One difference between ui-router and the abstract-state-router is that child states **do** have access to all parameters and resolve results from the parent states (assuming that they weren't overwritten by the child's parameters/resolve).

If named views were implemented in abstract-state-router, it would involve updating all of the renderers, since the passing in of the view name is done in the template, and the state router would have to start

1. asking each template for every ui-view instance
2. find which ones were named and which one was the generic child ui-view
3. tell every state/template to render itself at the correct element

and right now the renderers only need to return a single child element instead of N view children.

Right now, technically, a renderer could put children in a different element type - it's only by convention that they all use `ui-view` right now.  [Check out how the Riot renderer finds the element where the child state should go.](https://github.com/TehShrike/riot-state-renderer/blob/master/index.js#L51)

At the moment I think the only way to pull it off within the state-router would be to use your templating/rendering layer and add it yourself.  In this case, making a "navigation" Riot tag and embedding that in your app-layout.

I didn't implement named views because I didn't understand what they offered over directives/custom Riot tags/new Ractive instances or whatever the equivalent was in your chosen templating language.  But I probably missed something, and I'm not against implementing it.  Since named views exist in ui-router, I should probably either implement something to serve the same purpose, or at the very least explain in the documentation what the reasonable alternatives are (if there are any).

If there's anything that you lose moving to custom Riot tags instead of a named-view solution, please let me know - I'm still worried that I'm missing some killer feature in named views.

You can respond here, or in a new issue for named views if you like - I also set up a [gitter chat room](https://gitter.im/TehShrike/abstract-state-router) for some quicker back-and-forth if you're available.

**Pull request merged**
