### PR TITLE
queue stateRouter.go() if the state is transitioning

### PR DESCRIPTION
**Pull request by ArtskydJ**
Thoughts?

### CODE REVIEW

**Comment by TehShrike** [comment]
The implementation looks fine, but I'm starting to get antsy about adding more state to the StateProvider closure.  I wonder if it might be appropriate to start splitting things out to be more aggressively event-driven.

Like, maybe breaking this out into two module thingies - one that's responsible for knowing whether or not the module is in the middle of a state transition, and another that's responsible for launching the queue-up-states?

So, something like this at the top of StateProvider:

	var queueUpStateGo = stateQueueHandler(stateProviderEmitter)
	var insideStateTransitionRightNow = stateTransitionWatcher(stateProviderEmitter)

And then in state.go:

	if (insideStateTransitionRightNow()) {
		queueUpStateGo(arguments)
	} else {
		// current contents of state.go
	}

And then the state queue handler and transition watcher modules would just watch the emitter for state change start/end events to behave appropriately (the queue handler calling state.go on state change end, and the transition watcher just setting a boolean to true when a state change starts, and false when it ends).

It might seem a bit overengineered, but I think we're going to have to start fighting to keep the main closure clean.

**Comment by ArtskydJ** [comment]
I created an implementation, but the stateChangeStart event is not emitted synchronously. Other than that, it's working.

**Comment by ArtskydJ** [comment]
To prevent race conditions, an event should be emitted synchronously when a state change is attempted. Would it be reasonable to emit a 'stateChangeAttempt' event in state.go()? (Or in getDestinationUrl(), but the name doesn't fit.)

**Comment by ArtskydJ** [comment]
See #14 for updated version.

**Pull request closed without merging**
