### PR TITLE
Passing state parameters to renderer's render/reset functions

### PR DESCRIPTION
**Pull request by m59peacemaker**

### CODE REVIEW

**Comment by TehShrike** [comment]
hmm, I almost want to pass each renderer its own copy of the parameters object to prevent anybody futzing with state that other views can see.  What do you guys think?

**Comment by crissdev** [comment]
@TehShrike I don't any reason of passing them though. They can be made available, **when needed** through the returned data of the `resolve` method. But maybe I haven't came across a valid use case yet.

**Comment by TehShrike** [comment]
Ah yeah, context: @m59peacemaker is working on a React renderer.

It seems that React doesn't provide any way to programmatically interact with elements, and the functions that you attach to your React components have to initiate all contact with the outside world.  Somewhat similar to a Knockout view-model I suppose.

So @m59peacemaker was looking to avoid having states that need a resolve just to pass the parameters through.

I suppose this would only really be an issue for components that need to pay attention to parameters, but don't have to fetch anything asynchronously in order to render.

**Comment by m59peacemaker** [comment]
It would be lame if I'm wrong about needing them, but I would still feel like it would be ideal for the renderer to access them just in case. Cloning the params sounds good, but at the same time, does it really matter? It's wrong to mutate that object whether it's a local copy or the one accessible in other places.. the code is bad either way at that point. Maybe it would be better if someone were to change it that it has as many bad effects as possible so that they fix it? Dunno.

**Comment by crissdev** [comment]
`Object.freeze` might be enough to protect the parameters object.

**Comment by ArtskydJ** [comment]
I would rather do a shallow copy of parameters than to freeze them, but it's not a big deal to me.

**Comment by TehShrike** [comment]
Sorry for the neglect - how do you still feel about this one @m59peacemaker ?

**Comment by m59peacemaker** [comment]
I like freeze, so I'm for merging the current commit, but whatevs you decide. I might not be able to make a demo for my react-renderer for a bit anyway, so no rush.

**Comment by TehShrike** [comment]
I'm looking at trying to use the abstract state router with [elm](http://elm-lang.org/), which uses virtual-dom to generate html based on pure functions/templates.  The activate function probably wouldn't see a lot of use in an elm state, since your business logic code is also the template acting as a pure function that produces HTML.

So, the renderer that triggers that function should have access to the parameters, and I'd like to merge this.

I've decided I prefer a defensive copy to a `freeze`, but I can change that before I publish.

**Pull request merged**
