### PR TITLE
State dom api events

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes https://github.com/TehShrike/abstract-state-router/issues/53

Not ready to merge yet, just opening for easy reading/commenting.

### CODE REVIEW

**Comment by ArtskydJ** [comment]
I don't like the choice of event names. Right now ASR emits *StateChangeStart* and *StateChangeEnd*. We should stick with a naming scheme. Right now it is *UpperCamelPascalWhateverCase*.

We can either deprecate the current events and add aliases (*state change start/end*) or rename the current event names before they're merged (*Before/AfterDestroy/CreateState*).

Other than that (and I didn't look extremely close) it looks good to me.

**Comment by TehShrike** [comment]
Quite right.  I'll change the events to match the camelCase convention.

**Comment by ArtskydJ** [comment]
lgtm

**Comment by TehShrike** [comment]
Published in 5.9.0

**Pull request merged**
