### PR TITLE
Expose current state name

### PR DESCRIPTION
**Pull request by subpx**

### CODE REVIEW

**Comment by TehShrike** [comment]
Thanks for the PR!

People have asked for this feature occasionally, but I've never heard a fantastic argument for it - it seems like it's usually more appropriate to use `stateIsActive`, or react to a [state change event](https://github.com/TehShrike/abstract-state-router#state-change), which exposes the relevant states at the time of the event firing.

That said, this does keep coming up, and though it exposes a bit of internal state, it doesn't really add any other complexity, so I'm open to adding it.

Some discussion topics: 

- the current params should be exposed, too, since they are part of the definition of an active state.  Should there be two getter methods, or a single one that returns `{ name, params }`?  I'm leaning towards a single one that returns both name and object
- what should the method name be?  Most of the other ASR methods are verbs, so there's not a lot of precedent in the API yet.  I'd want it to be pretty explicit, so I'm leaning towards something like `getActiveState`

Pinging other stakeholders for their thoughts: @daytonlowell @saibotsivad

**Comment by TehShrike** [comment]
(Also @subpx feel free to [join the chat on Discord](https://discord.gg/G8FrErC) if you want to spitball thoughts)

**Comment by saibotsivad** [comment]
I haven't needed this functionality yet in any of the CMS-like webapps I've built, so I haven't thought through how a person would be likely to want to use something like this.

It seems that if you have to wait for the `stateChangeEnd` to get the active state, couldn't you just do this?

```js
stateRouter.on('stateChangeEnd', state => {
    state.name // => app.panel.tab
})
```

Definitely with you on the more explicit name, `getActiveState` sounds closer, but I note that the internal call is to `lastCompletelyLoadedState` which makes me wary--what's the space between a state becoming "active" and being "completely loaded"? A name like `getLastCompletelyLoadedState` would be most explicit 😃 but a name like `getActiveState` might imply something untrue, maybe?

**Comment by TehShrike** [comment]
The `stateIsActive` method [checks `stateName`](https://github.com/TehShrike/abstract-state-router/blob/e80001740b65081918465c4c20b3ee714adfde12/index.js#L367-L368), so there's precedent for conflating "active" with "last completely loaded".

**Comment by saibotsivad** [comment]
I didn't think of that,  that sounds like`getActiveState` would be a fair name 👍

**Comment by TehShrike** [comment]
Have any thoughts @subpx?

**Comment by subpx** [comment]
I agree with the name change and returning the state name and params getActiveState sounds good to me. Another option could be stateRouter.stateIsCurrent(stateName, [stateParameters])

**Comment by TehShrike** [comment]
`stateIsCurrent` isn't a bad name to change `stateIsActive` to, not worth the breaking change for now I imagine.

If you rename the new method to `getActiveState` and make it return `{ name, parameters }` (which is what `lastCompletelyLoadedState.get()` should be returning already), I'm down with merging.

**Comment by subpx** [comment]
Thanks, that is done. Raised a PR to ad that to svelte-state-renderer too

**Comment by saibotsivad** [comment]
That test file should be renamed `test/getActiveState.js => test/get-active-state.js` and indented with tabs, but otherwise the PR looks reasonable to me and I give it a 👍

**Pull request merged**
