### PR TITLE
States look-up

### PR DESCRIPTION
**Pull request by atoumbre**
Just added a way to look for states. Useful in some situation

### CODE REVIEW

**Comment by TehShrike** [comment]
Interesting.  What's your use case?  I haven't needed this kind of functionality yet myself, though @saibotsivad was thinking of a use case for a "check to see if a state exists" function the other day.

**Comment by saibotsivad** [comment]
I worked around the thing I was wanting by making my routes better. I had a reusable modal component that I wanted to show/hide buttons in itself based on whether the current state had a particular child state. In the end, I made that modal a child state, which made data loading easier and simplified many other issues.

All that to say, I haven't seen a need for "check if state exists" yet.

**Comment by atoumbre** [comment]
This a use case. 
I wanted to select automatically the menu items corresponding to states on manual url enter. 
The issue I had was the fact that menu are nested (menu > submenu > tabbar ...)  
I have workarrond but the best and most elegant way was to current state (easy) and hack the code to get a way to figure out recursively parent state and select corresponding menus.

**Comment by atoumbre** [comment]
No, not a breadcumb menu.
I'm working on admin panel with a sidebar et over menu like sub menu or tab. So I have several controls acting as menu at different level but not a single control like a breadcumb.

**Comment by TehShrike** [comment]
This makes sense.  It would work - you could add metadata to the `data` object with the menu item name, and whether or not states should be included in the visible menus.

That said, this feels wrong to push a bunch of data structures into abstract-state-router, and then immediately ask for them back.  Why not make an array or map of all of your states, and access it yourself?  Then you could iterate over it and call `addState` on each state to push it into abstract-state-router - no need to shove it the library and then immediately ask for it back.

**Comment by atoumbre** [comment]
Thanks for Ideas, They make sens and helps me. but this is some comment :
1st. data is passed to state activate function of the current state but menu items to activate are in parent state hierarchy. So we still need to find a way to get that hirearchy.
2nd. Using states array is nice, but I need to put a hierarchy in place to get parent states. Could be easy or not but the thing is, stateRouter already has needed hierarchy.

**Comment by TehShrike** [comment]
hmm.  Maybe I should publish [state-string-parser.js](https://github.com/TehShrike/abstract-state-router/blob/494c8028b1a48b3ebb2fc6a5fead74dc46a9a1e7/lib/state-string-parser.js) in its own module, so that you could use it to get the state hierarchy for any given state name.

One of the reasons I'm pushing back on giving abstract-state-router more responsibility is because I've been thinking about how to avoid mutable state in future versions of abstract-state-router, where instead of calling a bunch of methods on ASR and having it change its internal state by transforming the inputs, you hand it a complete data structure that it just reads from directly.

**Comment by TehShrike** [comment]
I'm going to close this, though I am grateful for the idea/contribution.

I'm too scared of expanding the API, especially in a way that encourages people to rely on abstract-state-router state/internals.  Exposing this kind of API would make it much more difficult for people to consider transitioning to [the rewrite that might happen eventually](https://github.com/TehShrike/abstract-state-router/wiki).

**Pull request closed without merging**
