### PR TITLE
Added ability to provide a function for a default parameter

### PR DESCRIPTION
**Pull request by daytonlowell**

### CODE REVIEW

**Comment by saibotsivad** [comment]
This should probably update the `README.md` as well?

**Comment by daytonlowell** [comment]
I think the CI builds fail because I use `Object.fromEntries` that was added in Node 12. Should I just code that bit myself?

**Comment by TehShrike** [comment]
hrm, `fromEntries` should exist in at least later versions of node 12.  `Object.entries` should definitely be okay though, that one was added in ES2015 I think

**Comment by daytonlowell** [comment]
Do you want me to go back to using `Object.entries` and change the node version that CI runs against?

**Comment by daytonlowell** [comment]
`Object.entries` was ES2017, according to this: https://github.com/tc39/proposal-object-values-entries

**Pull request merged**
